name: 'Deploy to GitHub pages'

on:
  push:
    branches:
    - master

jobs:
  deploy:
    strategy:
      matrix:
        node: [12.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
        CI: true      
    steps:
    - uses: actions/checkout@master
    - name: Set access token
      run: git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Set user name
      run: git config --global user.name $GITHUB_ACTOR
    - name: 'Use Node.js ${{ matrix.node }}'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: 'Install dependencies'
      run: npm ci
    #- name: 'Run tests'
    #  run: npm run test
    - name: 'Deploy to "gh-pages" branch'
      run: npm run deploy
